[package]
name = "speck"
version = "1.1.0"
authors = ["ticki <Ticki@users.noreply.github.com>"]
description = "Implementation of the SPECK block cipher."
repository = "https://gitlab.redox-os.org/redox-os/speck"
documentation = "https://docs.rs/speck"
license = "MIT"
keywords = ["crypto", "cipher", "speck", "block", "simple"]
categories = ["cryptography", "no-std"]
exclude = ["target", "Cargo.lock"]

[dev-dependencies]
rand = { version = "0.3.16", features = ["i128_support"] }
